### ISSUE TITLE
Lava is being generated in the nether instead of blood, again

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/hypovolemia#123]
title says the problem, i found a gigantic pool of lava in the nether, i went around and explored it, caused tps to drop (indicating new chunk generation, nothing else has been choking the server by 4-5 tps) annnnd it was still lava

**Comment by shaggy1395** [comment]
I definitely had lava instead of blood, didn't know to report it though since I didn't know the plan for the nether.  And from a previous hint from drz2k "don't ask how to get glowstone", I found that rather easy as well since it was just standard glowstone on the ceiling in the nether.  Not sure if that was intentional or not.

**Comment by Sandstroem** [comment]
Please note that the spawn of ghasts seems to be related to the lava in some yet to determine way.

**Comment by drz2k** [comment]
note to myself - implement ghast tear recipe - then ignore worldgen and close this :)

**Comment by tyler489** [comment]
I killed 12 ghasts in .13 for the 8 tears to advance. they spawn

**Comment by metalim** [comment]
Ghasts spawn randomly. When I visited Nether for the first time, they were shooting at me right away. Next time, I killed 3 ghasts in 10 minutes and then waited 3 or 4 hours for the next to spawn.
