### ISSUE TITLE
Seeds not gainig levels

### ISSUE THREAD

**Issue by EpicDragonLord15** [MyM-ModpackTeam/hypovolemia#173]
i've created a place to level my agricraft crops but i cans teem to get my seeds to level any more, i tested with normal seeds and essence seeds, the normal seeds wont go past 1-2-1 and essence seeds 1-1-1
Start:
![2016-03-31_17 31 45](https://cloud.githubusercontent.com/assets/15305693/14168714/3ad5266a-f767-11e5-9c98-619805f2d039.png)
![2016-03-31_17 31 47](https://cloud.githubusercontent.com/assets/15305693/14168720/41e0b0dc-f767-11e5-89d8-545d6f799cfe.png)
end:
![2016-03-31_17 36 39](https://cloud.githubusercontent.com/assets/15305693/14168730/4d55d302-f767-11e5-97b4-97b25448e7c8.png)
![2016-03-31_17 36 46](https://cloud.githubusercontent.com/assets/15305693/14168734/550b0b1c-f767-11e5-8d84-a1b2809256c9.png)

**Comment by Sandstroem** [comment]
That is probably because you have played too much Regrowth. Seeds do not spread like in Regrowth, where you can set up a line and let them do their thing. In Hypovolemia you have to level seeds by crossbreeding two or more of the same seeds. So you really have to do that manually. There are multiple ways though to get a seed really fast up to 10-10-10.
Sigil of the green grove helps of course as well as the abundance of bone meal.

Easiest way is to set them in a line X-O-X, where X are two fully grown parent seeds and O is the double cropstick where you want your child to go. Even better in a 2x2, where you set the parents in the opposite corners and then alternate.

**Comment by EpicDragonLord15** [comment]
ok, thanks
i never knew that
