### ISSUE TITLE
dupe bug with draw's

### ISSUE THREAD

**Issue by JarlGiga** [MyM-ModpackTeam/hypovolemia#178]
so when smelting oreberrys you get 2-3 ingots out of it, then craft them into nuggets, and put them into a draw with oreberrys, and the nuggets will ore dicted into berrys, and now you just made 9x

**Comment by chuggafan** [comment]
oh dang, i thought i had this fixed when i reported the MFR ore dict thing, can someone please handle this ASAP and just remove oreberrys from the oredict for nuggets?

**Comment by Sandstroem** [comment]
The old links:

https://github.com/MyM-ModpackTeam/hypovolemia/issues/56
https://github.com/MyM-ModpackTeam/hypovolemia/commit/479517a6fa02572d2c04e1ffb95096276f183385
https://github.com/MyM-ModpackTeam/hypovolemia/issues/113
https://github.com/MyM-ModpackTeam/hypovolemia/commit/647010a17e2c1cb93fb022f0bf29bb307d2109e0

The issue is obviously in the recipes and not in those blocks. Or do we want to remove Storage Drawers also?

The suggestion from chugga sounds better, if that is possible.

**Comment by johnfg12** [comment]
all right il sort this in a bit. chuggas method seems perfect and easy to implement too :)
