### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by krakel** [MyM-ModpackTeam/hypovolemia#355]
I was getting a StackOverflowError on my old world after update to 0.1.8. I created a new server. The log of the world creation show the same error.
http://pastebin.com/uvL9NFBw
Thaumcraft parse all recipes and found a loop.

**Comment by kindlich** [comment]
First of all, we need some more information since we tested it on local servers and it worked fine there...

- Are you using a "normal" Forge Server or something like KCauldron(Forge + Plugins)?

- What Version is your server on (not 1.7.10, thats obvious, but the forge Version, like 1614/1558)?

- Did you re-check with a clean copy of hypo?

- What Version of Java are you using?


One more thing: Could you check, whether your Version of Thaumcraft is correct?
The Log clearly sais, it finished loading all of that tagging, but it couldn't find the "tempus" aspect...

`[00:19:59] [Server thread/DEBUG] [FML/MineFactoryReloaded|CompatThaumcraft]: [CoFH Thaumcraft Helper] tempus aspect missing.` <-- Self-Explaining

**Comment by krakel** [comment]
1. download the latest version server 0.1.8 from github
2. expand the server files on a new directory
3. change the eule to true
4. start the ServerStart-Windows.bat

After finish the start routine inspect the last 10% of the fml-server-latest.log. You will find the StackOverflowError. 
My Java version = 1.8.0_91
The same error I got after the update of my long played 0.1.7 game to 0.1.8. Every time I want Shift-Click some items between inventories my client crashed with these error.

**Comment by kindlich** [comment]
Ok, now I see your error, but that Stackoverflow Error exists in many versions already, it's not a new one that got added in the updating process...

I still have archives going back one or two months and they have the same error logged...

**Comment by krakel** [comment]
I found a discussion here https://github.com/CoFH/Feedback/issues/604
After I changed the property on the WitchingGadgets config the StackOverflowError was gone. But I dont know the impact of this change to the game.

**Comment by chuggafan** [comment]
Doing that would do just about nothing important, so it should be fine
