### ISSUE TITLE
Repost from ticket system

### ISSUE THREAD

**Issue by bookerthegeek** [MyM-ModpackTeam/hypovolemia#371]
https://mineyourmind.net/ticket/ticket/view/13836

**Comment by kindlich** [comment]
Could you please describe the issues here?
The ones without moderator status (such as me or stud) cannot look into that ticket...

**Comment by johnfg12** [comment]
Upon attempting to create the hammer head cast in the alchemy set, it will only create a pickaxe head cast due to it detecting the pickaxe I assume, making it unable to make the hammer head cast.

Okay. The recipe conflicts with a another recipe in Blood Magic's Alchemy Set. To craft the hammer head cast, you need to put in a blank cast and three iron pickaxes. There is also a recipe for the pickaxe head which requires a blank cast and one iron pickaxe. Unfortunately, if you try to make the hammer head cast; you will be unsuccessful in doing so due to it detecting the iron pickaxes and seeming not to count how many iron pickaxes you have in, it only makes a pickaxe head cast. I haven't found a way around this, no matter what I have done to try and make a hammer head cast. I have attempted putting the pickaxes in, then the cast, but it still made a pickaxe head cast. I tried to rush putting the pickaxes in, but it still made a pickaxe head cast. I'm sorry for my absence on this ticket by the way, I've been quite busy with things in real life.

**Comment by stijn04356789** [comment]
Quote from the ticket:

**Okay. The recipe conflicts with a another recipe in Blood Magic's Alchemy Set. To craft the hammer head cast, you need to put in a blank cast and three iron pickaxes. There is also a recipe for the pickaxe head which requires a blank cast and one iron pickaxe. Unfortunately, if you try to make the hammer head cast; you will be unsuccessful in doing so due to it detecting the iron pickaxes and seeming not to count how many iron pickaxes you have in, it only makes a pickaxe head cast. I haven't found a way around this, no matter what I have done to try and make a hammer head cast. I have attempted putting the pickaxes in, then the cast, but it still made a pickaxe head cast. I tried to rush putting the pickaxes in, but it still made a pickaxe head cast. I'm sorry for my absence on this ticket by the way, I've been quite busy with things in real life.**

**Comment by Sandstroem** [comment]
Hm, I am sure this was already posted ages ago and I thought it was fixed.

I suggest to make the recipe for the hammer head use 3 diamond pickaxes instead of 3 iron pickaxes. This should hopefully not conflict with any other recipe.

**Comment by krakel** [comment]
on 0.1.8 it was not fixed
```
addRecipe(castAxeHead,[patternBlank1,ironaxe],2,1000);
addRecipe(castBroadAxeHead,[patternBlank,ironaxe,ironaxe,ironaxe],3,5000);
addRecipe(castBroadAxeHead,[patternBlank1,ironaxe,ironaxe,ironaxe],3,5000);

addRecipe(castShovelHead,[patternBlank1,ironshov],2,1000);
addRecipe(castExcahatorHead,[patternBlank,ironshov,ironshov,ironshov],3,5000);
addRecipe(castExcahatorHead,[patternBlank1,ironshov,ironshov,ironshov],3,5000);

addRecipe(castPickHead,[patternBlank1,ironpick],2,1000);
addRecipe(castHammerHead,[patternBlank,ironpick,ironpick,ironpick],3,5000);
addRecipe(castHammerHead,[patternBlank1,ironpick,ironpick,ironpick],3,5000);
```

**Comment by tyler489** [comment]
Someone changed it i had the tier 2 use diamond parts...

**Comment by johnfg12** [comment]
should be fixed
